name = "tchrResearch"
uuid = "abfa16e4-84c2-49c1-b040-8fed6dc98604"
repo = "https://github.com/thchr/tchrResearch.git"
description = "Registry containing private research packages by Thomas Christensen (tchr@mit.edu) and contributors"

[packages]
ae5e2be0-a263-11e9-351e-f94dad1eb351 = { name = "Crystalline", path = "C/Crystalline" }
ba71f38f-f508-439b-ac77-437f86a20aa1 = { name = "SmithNormalForm", path = "S/SmithNormalForm" }
cb68ded9-7e8c-45d3-bc66-19b5867c0467 = { name = "SymmetryBases", path = "S/SymmetryBases" }
d7bc101a-f969-4292-96d7-1ebdabfa903f = { name = "PhotonicBandConnectivity", path = "P/PhotonicBandConnectivity" }
